apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-dev
  namespace: dev
  labels:
    app: appointment-service-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service-dev
  template:
    metadata:
      labels:
        app: appointment-service-dev
    spec:
      containers:
      - name: appointment-service-dev
        image: appointmentservice.azurecr.io/appointment-service-dev:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3001"
      imagePullSecrets:
      - name: acr-secret