apiVersion: v1
kind: Service
metadata:
  name: patient-service-dev
  namespace: dev
  labels:
    app: patient-service-dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: patient-service-dev