apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-dev
  namespace: dev
  labels:
    app: patient-service-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-service-dev
  template:
    metadata:
      labels:
        app: patient-service-dev
    spec:
      containers:
      - name: patient-service-dev
        image: patientservice.azurecr.io/patient-service-dev:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3000"
      imagePullSecrets:
      - name: patientservice-acr-secret